name: Deploy VM to Azure using Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.6.6'
      
      # Configure Azure login using Azure CLI (Azure credentials should be set as secrets in GitHub)
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Initialize Terraform
      - name: Terraform Init
        run: terraform -chdir=Terraform/virtual_machine init -input=false -no-color -reconfigure

      # Validate Terraform files
      - name: Terraform Validate
        run: terraform -chdir=Terraform/virtual_machine validate -no-color

      # Terraform Plan
      - name: Terraform Plan
        run: terraform -chdir=Terraform/virtual_machine plan -input=false -no-color

      # Terraform Apply
      - name: Terraform Apply
        run: terraform -chdir=Terraform/virtual_machine apply -auto-approve -input=false -no-color

      # Clean up the environment (Optional)
      - name: Terraform Destroy
        if: ${{ always() }}
        run: terraform -chdir=Terraform/virtual_machine destroy -auto-approve -input=false -no-color
