name: Deploy VM to Azure using Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.6.6'

      - name: Create terraform.tfvars
        run: |
          cat <<EOF > Terraform/virtual_machine/terraform.tfvars
          subscription_id = "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
          client_id       = "${{ secrets.AZURE_CLIENT_ID }}"
          client_secret   = "${{ secrets.AZURE_CLIENT_SECRET }}"
          tenant_id       = "${{ secrets.AZURE_TENANT_ID }}"
          location        = "East US"
          admin_username  = "adminuser"
          admin_password  = "${{ secrets.ADMIN_PASSWORD }}"
          EOF

      - name: Terraform Init
        run: terraform -chdir=Terraform/virtual_machine init -input=false -no-color -reconfigure

      - name: Terraform Validate
        run: terraform -chdir=Terraform/virtual_machine validate -no-color

      - name: Terraform Plan
        run: terraform -chdir=Terraform/virtual_machine plan -input=false -no-color

      - name: Terraform Apply
        run: terraform -chdir=Terraform/virtual_machine apply -auto-approve -input=false -no-color

      - name: Terraform Destroy
        if: ${{ always() }}
        run: terraform -chdir=Terraform/virtual_machine destroy -auto-approve -input=false -no-color
